Document: universal
Title: Debian universal Manual
Author: <insert document author here>
Abstract: This manual describes what universal is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/universal/universal.sgml.gz

Format: postscript
Files: /usr/share/doc/universal/universal.ps.gz

Format: text
Files: /usr/share/doc/universal/universal.text.gz

Format: HTML
Index: /usr/share/doc/universal/html/index.html
Files: /usr/share/doc/universal/html/*.html
